name: OneShot
options:
  bundleIdPrefix: com.oneshot
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  OneShot:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: OneShot
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oneshot.app
        INFOPLIST_FILE: OneShot/Info.plist
        GENERATE_INFOPLIST_FILE: "NO"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
    entitlements:
      path: OneShot/OneShot.entitlements

schemes:
  OneShot:
    build:
      targets:
        OneShot: all
    run:
      config: Debug
    archive:
      config: Release
